### ISSUE TITLE
Unable to start valhalla-scripted with custom_files set as read-only

### ISSUE THREAD

**Issue by Kainsin** [valhalla/valhalla#5672]
I am using the Docker image and I've recently updated from version `3.3.0` to `3.6.0` and tying `custom_files` to a read-only file system does not appear to be working. I am getting the follow error in the logs:

```
INFO: Found routing tiles with 'use_tiles_ignore_pbf' True.
INFO: Jumping directly to the tile loading!
error opening output file: Read-only file system
```

Looking through the Docker script and code a bit, it appears that setting `update_existing_config` to `False` is needed to prevent doing anything to `valhalla.json` on startup, however I believe something in `valhalla/config` or `rapidjson::read_json` wants to open this file in read/write mode.

If there is a setting I am missing then I am all ears. Thanks!

**Comment by nilsnolde** [comment]
@Kainsin thanks, seems to be an issue outside the `if update_existing_config == True`, see https://github.com/valhalla/valhalla/pull/5675/files#diff-8e326a8b1b42f59ef942167d08072b2388e3f529ab558de1a4ec08d16cc5dce3. 

the `sponge` command is opening the config. I'm not sure if that doesn't bomb smth else. I changed CI real quick to spit out an image. in a bit you should be able to pull it from `ghcr.io/valhalla/valhalla-scripted:issue5672` (should also pop up here: https://github.com/valhalla/valhalla/pkgs/container/valhalla-scripted).

Would you mind giving that image a try in case it successfully builds?

**Comment by Kainsin** [comment]
No luck, unfortunately. I'm using this:

`sudo docker run -dt --name valhalla -p 8002:8002 -v /my/tile/path:/custom_files:ro -e update_existing_config="False" -e force_rebuild="False" -e use_tiles_ignore_pbf="True" ghcr.io/valhalla/valhalla-scripted:issue5672-arm64`

and am still seeing the error:

```
find: '/custom_files/transit_tiles': No such file or directory
INFO: Found routing tiles with 'use_tiles_ignore_pbf' True.
INFO: Jumping directly to the tile loading!
INFO: Found existing valhalla.json at /custom_files/valhalla.json
error opening output file: Read-only file system
```

However it does now have `INFO: Found existing valhalla.json at /custom_files/valhalla.json`

**Comment by nilsnolde** [comment]
at least that's confirming that it built properly.

hm, that's strange. I'll try myself. in libvalhalla nothing should write to the valhalla.json, so it should be the docker instrumentation.

**Comment by Kainsin** [comment]
I'm wondering if it's something [here](https://github.com/valhalla/valhalla/blob/master/src/config.cc#L21-L26)?

There was a [somewhat recent commit](https://github.com/valhalla/valhalla/commits/master/src/config.cc) to replace `valhalla/filesystem` with `std`. Is it trying to open the file in read/write now but before it was being opened in read-only mode?

**Comment by nilsnolde** [comment]
hm, not sure I see what exactly you want to point at, sorry.. can you point out the exact line where smth is opening the config file in read/write mode?

**Comment by nilsnolde** [comment]
AFAICT it's all still `std::ifstream` in rapidjson::read_json(): https://github.com/valhalla/valhalla/blob/6db8cae77c371ae0af447578a93139023cae8318/valhalla/baldr/rapidjson_utils.h#L235

**Comment by Kainsin** [comment]
Gotcha, it was just my best guess from looking at the script and code. It seems like `valhalla_service` was being called, so it was passing the Docker entrypoint script and since it error'ed out quickly my hunch was somewhere in `config.cc` trying to read it.

**Comment by nilsnolde** [comment]
if it would've started valhalla_service already, you should've at least seen a line with `echo "INFO: Found config file. Starting valhalla service!" in the logs. also just realizing we're talking about a r/o file_system_. I'm pretty sure nothing in valhalla_service writes to disk (yet).

maybe it's these lines?

https://github.com/valhalla/valhalla/blob/32048247ae7e39f1a0acb921a4501176cfab1bf3/docker/scripts/docker-entrypoint.sh#L39-L40

a r/o filesystem probably doesn't allow modifying permission to be able to _write_ 😅  that's honestly more of a convenience so you don't have to use sudo on the host to write to those files. we can maybe protect it with some test to see if the filesystem is writable?

**Comment by nilsnolde** [comment]
but I'm still pretty sure the issue I fix in the PR is also valid and would be a problem for your system. seems it's 2 bugs.. on top of that I just saw that we didn't test that docker image in months due to a CI bug..

**Comment by nilsnolde** [comment]
I gave it another shot at http://github.com/valhalla/valhalla/pull/5675/files#diff-50d980f599e507249674ef4629adbcdae668187d918eaf240bb5e4a477a284d0. in a few mins you can try again, should work now 🤞 

this gha needs to pass: https://github.com/valhalla/valhalla/actions/runs/19084430962/job/54521332021?pr=5675

**Comment by Kainsin** [comment]
Sadly I'm still getting the same error. No change in the logs from last time.

I did make sure to pull to get the latest image.

**Comment by nilsnolde** [comment]
Oh man I'm sorry.. Now it's starting to piss me off! I'll create a r/o FS later myself and add a test while I'm at it..

**Comment by Kainsin** [comment]
I noticed your change to the `chmod` portion of the script added two `INFO` logs. I don't see either showing up, if that helps narrow down where the problem is.

**Comment by nilsnolde** [comment]
It does suggest that you're not using the latest one. Do note that the last push published properly so it's without the -arm64 suffix.

**Comment by Kainsin** [comment]
I tried both with the same result. This is what I'm running (I did a pull to verify it was the latest image):

```
docker run -dt --name valhalla -p 8002:8002 -v /my/tile/path:/custom_files:ro -e update_existing_config="False" -e force_rebuild="False" -e use_tiles_ignore_pbf="True" ghcr.io/valhalla/valhalla-scripted:issue5672
```

and this is the log:

```
find: '/custom_files/transit_tiles': No such file or directory
INFO: Found routing tiles with 'use_tiles_ignore_pbf' True.
INFO: Jumping directly to the tile loading!
INFO: Found existing valhalla.json at /custom_files/valhalla.json
error opening output file: Read-only file system
```

**Comment by Kainsin** [comment]
Looking at the code changes and the log, I am seeing your change to this log:
`INFO: Found existing valhalla.json at /custom_files/valhalla.json`

**Comment by Kainsin** [comment]
I played around locally and found it. There's another `sponge` call in the `configure_valhalla.sh` script where it's checking the default speed. If I set `use_default_speeds_config` to `False` then it skips this and things work fine (using your other changes), but I assume the correct solution would be to wrap that line with a check for `update_existing_config` since it's trying to update `valhalla.json`?

**Comment by nilsnolde** [comment]
ah cool, I can see what you mean. even before the sponge command it'd try to download the speeds json to the r/o FS. what's missing is that this shouldn't be even called when only used as service. we only need that file when we build data.

I just completed the PR, also added a docker test case. you don't need to set `use_default_speeds_config` anymore, it'll auto-detect when you're on a r/o FS.

**Comment by Kainsin** [comment]
Thank you!

**Comment by Kainsin** [comment]
I verified that the latest issue5672 image works with only `update_existing_config="False" force_rebuild="False" use_tiles_ignore_pbf="True"`

**Comment by nilsnolde** [comment]
good that it works for you! also works for me. but not for CI for some reason.. FWIW, you shouldn't even need `update_existing_config="False"` anymore with a r/o fs

**Comment by Kainsin** [comment]
Any ETA on when this might be merged in? Or could another branch release be made off of the 3.6.1 release?

**Comment by Kainsin** [comment]
@nilsnolde I see that the PR for this was closed last month. Is this still an open issue or was it fixed in another PR?
